name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  local_auth: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.5+1
  sqflite: ^2.3.2
  wheel_slider: ^1.2.2
  share_plus: ^11.1.0
  flutter_local_notifications: ^19.4.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.25.15
  sqflite_common_ffi: ^2.3.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/tutorial/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.webp"
